name: C++ CLI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Windows:
    runs-on: windows-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
    
      - name: Install Conan
        run: |
          pip install conan
        shell: cmd
      
      - name: Conan
        run: |
          cd C++
          mkdir build
          cd build
          conan install ..
          cd ..
        shell: cmd
        working-directory: ./C++/
      
      - name: Build with Cmake
        run: |
          cmake -B ./build
          cmake --build ./build --config Release
        shell: cmd
        working-directory: ./C++/
          
          
      - name: Upload Windows Executable
        uses: actions/upload-artifact@v2.2.0
        with:
          name: Windows x64
          path: ./C++/build/bin/gapt.exe
