# This is a basic workflow to help you get started with Actions

name: C++

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
      
      - name: Build with Cmake
        run: |
          cd C++
          mkdir build
          cd build
          conan install ..
          cmake .. -G "Visual Studio 16 2019"
          cmake .. --config release --target ALL_BUILD
          
          
      - name: Upload Windows Executable
        uses: actions/upload-artifact@v2.2.0
        with:
          name: Windows x64
          path: ./C++/build/bin/gapt.exe
